### ISSUE TITLE
Kodi V19 - Android 11 problem

### ISSUE THREAD

**Issue by lefty10** [primaeval/plugin.video.iptv.recorder#53]
I'm using the addon version for Kodi V19  by @Dobi-Dev (https://github.com/Dobi-Dev/plugin.video.iptv.recorder).
It worked on Android 9 but when upgraded to Android 11, it failed because of ffmpeg permissions:
See [Kodi_error.txt](https://github.com/primaeval/plugin.video.iptv.recorder/files/7965486/Kodi_error.txt)

I know that Android 11 added many restrictions on using files.
Does ffmpeg need to be placed on different directory other than /data/data/... in order to overcome the permission  problem ?

**Comment by tbrek** [comment]
It very likely that it's the SDK issue. You might need to update ffmpeg to the later version.

**Comment by lefty10** [comment]
I updated ffmpeg to latest. Same error.

**Comment by Dobi-Dev** [comment]
I don't have android 11, so I can't check on my side.
But yes, you can try to change ffmpeg location.
In all case, the ffmpeg file must have be allowed to be executed by all users. It is possible that some files explore application let you change these rights manually.

Best regards.

**Comment by lefty10** [comment]
I changed ffmpeg location to kodi userdata location and changed ffmpeg permissions to have execute ability to all.
I changed the permissions from the addon itself.
But unfortunately i get the same error.

**Comment by Dobi-Dev** [comment]
Unfortunately, you can no more start another binary stored in the app data folder.
Have a look at https://stackoverflow.com/questions/60370424/permission-is-denied-using-android-q-ffmpeg-error-13-permission-denied

**Comment by Mariusz89B** [comment]
This issue might be solved if Kodi decided to ship ffmpeg binary, then it would be possible to execute it on Android 11.
https://github.com/Mariusz89B/script.mtvguide/issues/18#issuecomment-1195090394

**Comment by Shtolzer** [comment]
I have a rooted phone on Android 11.
primaeval/plugin.video.iptv.recorder works in Kodi version 18.9 (Leia)
Doesn't work in version 19.0 (Matrix) and shows a different error than yours:
`2024-07-25 11:39:59.522 T:28765   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.iptv.recorder/context.py", line 13, in <module>
                                                       channel = channel.decode("utf8")
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--`
